[package]
name = "bevy_ortho_cam"
version = "0.1.0"
edition = "2021"


[dependencies]
bevy = { git = "https://github.com/bevyengine/bevy", rev = "c04dfc1174729781219c257fdd1e379a2f1a1a52" }

[profile.dev]
opt-level = 3
